# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target ‘TriviaApp' do
    pod 'Alamofire', '~> 4.5'
    pod 'CardViewList', '~> 1.1.8'
    pod 'JGProgressHUD'
end
